# Sample Configuration File for Your Application

# Database Configuration
[database]
db_type = "mysql"
db_host = "thinkbricks-db.ct00o317q97i.us-east-1.rds.amazonaws.com"
db_port = 3306
db_name = "ecommerce_sample"
db_user = "admin"
db_password = "password"

# Caching Configuration
[caching]
cache_enabled = true
cache_expiry = 3600
cache_type = "memcached"
cache_host = "memcache"
cache_port = 11211

# Other Parameters
[schema]
fetch_schema = true
relationship_file = "data/relationships.json"
schema_file = "data/table_schema_db.json"

# Caching Configuration
[authentication]
authenticate = true
authority = ""
